### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by deniciocode** [amadeus/vim-mjml#1]
Hey,

I tried out this plugin, but it does not highlight my MJML file. Do I need some special configurations to highlight my file? 

EDIT:

I am new to MJML. As I see, we are using MJML with HAML. Maybe this is the issue.

**Comment by amadeus** [comment]
The file extension must be `mjml`, you can also try `:set filetype=mjml` if the file is by default another filetype.

**Comment by deniciocode** [comment]
Hey @amadeus,

this has nothing todo with the filetype. It is set correctly. The issue is the usage of [haml](http://haml.info/) syntax.
We are using haml inside our rails application for our views and mails.
Now we switched from `haml` to `haml.mjml`. If I switch the filetype to `haml` it works by the syntax highlighting of haml.
