### ISSUE TITLE
Style highlight not working

### ISSUE THREAD

**Issue by sobrinho** [amadeus/vim-mjml#3]
<img width="1188" alt="Screen Shot 2021-08-30 at 11 21 53" src="https://user-images.githubusercontent.com/26460/131354238-725d2a6c-e2dd-4980-b7c4-76e07c73887a.png">

**Comment by amadeus** [comment]
I haven't really worked on this project in a while, since I don't really have a current need for it atm. Happy to take PRs if someone wants to take this on though!

**Comment by adamkusmirek** [comment]
added a pull request #4

further testing is advised :smile:

**Comment by amadeus** [comment]
Thanks for the PR, it has been merged!
